# --- QMix with a Transformer Mixer---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000 

runner: "episode"
buffer_size: 5000 
batch_size: 32

# update the target network every {} episodes
target_update_interval: 200

# parameters of the agent
mac: "n_mac"
agent: "n_rnn"
rnn_hidden_dim: 64
agent_output_type: q

# parameters of the transformer mixer
mixer: "transf_mixer"
emb: 64
mixer_emb: 64 # embedding dimension of transformer (must be the same of the rnn agent, 64 by default)
mixer_heads: 4 # head number of transformer
mixer_depth: 2 # block number of transformer
qmix_pos_func: "abs" # function to impose monotonic constraint
ff_hidden_mult: 4 # relative dimension of hidden layer of ff after attention
dropout: 0 # multi-head attention dropout

# paramters for the learner 
learner: "nq_transf_learner"
weight_decay: 0
optimizer: "adam"
lr: 0.001
td_lambda: 0.6

env_args:
  obs_entity_mode: False
  state_entity_mode: True

name: "qmix_transf_mixer"
