# --- QMIX specific parameters with large networks ---
# for 3s5z_vs_3s6z

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000 

runner: "episode"
buffer_size: 5000 
batch_size: 32

# update the target network every {} episodes
target_update_interval: 200

# parameters of the transformer agent
mac: "n_mac"
agent: "updet_smac"
agent_output_type: q
emb: 32 # embedding dimension of transformer
heads: 4 # head number of transformer
depth: 2 # block number of transformer
ff_hidden_mult: 4 # relative dimension of hidden layer of ff after attention
dropout: 0. # multi-head attention dropout

learner: "nq_learner"
mixer: "qmix"
mixing_embed_dim: 32
hypernet_embed: 64
q_lambda: False
optimzer: "adam"

# to keep the token dimension fixed, observaion id and last action should not be included
obs_agent_id: False # Include the agent's one_hot id in the observation
obs_last_action: False # Include the agent's last action (one_hot) in the observation
obs_entity_feats: 5 # assumes working with marines

name: "updet_smac"
